image: Visual Studio 2019

init:
- git config --global core.autocrlf true

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
- cmd: "dotnet publish \"./Tools/rdmp\" -r win-x64 /v:q"
- ps: "./Tools/rdmp/bin/Debug/netcoreapp3.1/win-x64/rdmp.exe install localhost TEST_ -D -u sa -p Password12!"
  
build_script:

- ps: Remove-Item .\Tests.Common\TestDatabases.txt
- ps: Rename-Item .\Tests.Common\Appveyor.TestDatabases.txt TestDatabases.txt
- ps: dotnet build HIC.DataManagementPlatform.sln /v:q
- ps: dotnet test -p:BuildInParallel=false dirs.proj


test: off

services:
  - mssql2017

